name: Some manual workflow
on: [workflow_dispatch]
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Cat file
        run: cat test.txt