name: Some manual workflow
on:
  schedule:
    - cron: '05 17 * * *'
  workflow_dispatch:
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Set up correct branch environment variable
        run: |
          if [ $GITHUB_EVENT_NAME == "schedule" ]; then
            echo "Running via schedule, so using branch api-call"
            echo "NIGHTLY_BUILD_REF=api-call" >> $GITHUB_ENV
          else
            echo "Not running via schedule, so using branch $GITHUB_REF_NAME"
            echo "NIGHTLY_BUILD_REF=$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi
      - name: Print env
        run: env
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.NIGHTLY_BUILD_REF }}
      - name: Cat file
        run: cat test.txt
