name: Some manual workflow
on:
  schedule:
    - cron: '05 17 * * *'
  workflow_dispatch:
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}
      - name: Cat file
        run: cat test.txt